# -*- coding: utf-8 -*-
"""customer_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-VWJXPMaMxHSf8nBZ-995gD5JP6Kw1Zk
"""

!pip install streamlit

from google.colab import drive
drive.mount('/content/drive')

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/customer_sale.csv')

# Title and description
st.title("Customer Sales Dashboard")
st.markdown("An interactive dashboard for exploring customer sales data.")

# KPI Metrics
total_sales = df["Sale"].sum()
avg_order_value = df["Sale"].mean()
total_orders = df.shape[0]

st.metric("Total Sales", f"${total_sales:,.2f}")
st.metric("Average Order Value", f"${avg_order_value:,.2f}")
st.metric("Total Orders", total_orders)

# Monthly Sales Trend
st.subheader("Monthly Sales Trend")
monthly_sales = df.groupby("Purchase Month")["Sale"].sum()
fig, ax = plt.subplots()
monthly_sales.plot(kind="line", marker="o", ax=ax)
ax.set_xlabel("Month")
ax.set_ylabel("Sales")
ax.set_title("Sales by Month")
st.pyplot(fig)

# Sales by Product Category
st.subheader("Sales by Product Category")
category_sales = df.groupby("Product Category")["Sale"].sum().sort_values(ascending=False)
st.bar_chart(category_sales)

# Filter by year
st.subheader("Filter by Year")
year = st.selectbox("Select Year", sorted(df["Purchase Year"].unique()))
filtered = df[df["Purchase Year"] == year]
st.write(f"Filtered Data for Year {year}", filtered)